// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0YrACKxyVOWp8VcOrqHclTWEcADBxxBg',
    appId: '1:414568163828:web:f970c5b752b0d36ac5f1a1',
    messagingSenderId: '414568163828',
    projectId: 'gogleexample-a067a',
    authDomain: 'gogleexample-a067a.firebaseapp.com',
    storageBucket: 'gogleexample-a067a.firebasestorage.app',
    measurementId: 'G-88K5G6VCBY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKBxXY2hnTvysgTbe_Z8Ntz6uQ3M2UNhQ',
    appId: '1:414568163828:android:bf5a8a282594a0a8c5f1a1',
    messagingSenderId: '414568163828',
    projectId: 'gogleexample-a067a',
    storageBucket: 'gogleexample-a067a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEiMShUvga64GP60zLDm0vjPKdQiZWF_k',
    appId: '1:414568163828:ios:53666ed02a66c730c5f1a1',
    messagingSenderId: '414568163828',
    projectId: 'gogleexample-a067a',
    storageBucket: 'gogleexample-a067a.firebasestorage.app',
    iosBundleId: 'com.example.sccSurveyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEiMShUvga64GP60zLDm0vjPKdQiZWF_k',
    appId: '1:414568163828:ios:53666ed02a66c730c5f1a1',
    messagingSenderId: '414568163828',
    projectId: 'gogleexample-a067a',
    storageBucket: 'gogleexample-a067a.firebasestorage.app',
    iosBundleId: 'com.example.sccSurveyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0YrACKxyVOWp8VcOrqHclTWEcADBxxBg',
    appId: '1:414568163828:web:f54a7fb94a99b336c5f1a1',
    messagingSenderId: '414568163828',
    projectId: 'gogleexample-a067a',
    authDomain: 'gogleexample-a067a.firebaseapp.com',
    storageBucket: 'gogleexample-a067a.firebasestorage.app',
    measurementId: 'G-TE0HBE37ZS',
  );
}
